"""initial migration

Revision ID: 3476fd1e1868
Revises: 
Create Date: 2025-04-13 18:56:40.593989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3476fd1e1868'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom_skill')
    with op.batch_alter_table('mission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xp_reward', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('failed', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_failed')
        batch_op.drop_column('deadline')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadline', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('is_failed', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('failed')
        batch_op.drop_column('xp_reward')

    op.create_table('custom_skill',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('level', sa.FLOAT(), server_default=sa.text('1'), nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('category_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('category_color', sa.VARCHAR(length=20), nullable=True),
    sa.Column('icon', sa.VARCHAR(length=10), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
